-- HW2.sql -- Homework 2
--
-- KEVIN NGUYEN
-- UT EID: kdn433, UTCS username: kxnguyen
-- CS f347, Spring 2017, Dr. P. Cannata
-- Department of Computer Science, The University of Texas at Austin
--
 
-- 4-01
SELECT CATEGORY_NAME, PRODUCT_NAME, LIST_PRICE FROM CATEGORIES INNER JOIN PRODUCTS
ON CATEGORIES.CATEGORY_ID = PRODUCTS.CATEGORY_ID
ORDER BY CATEGORY_NAME, PRODUCT_NAME;

-- 4-02
SELECT FIRST_NAME, LAST_NAME, LINE1, CITY, STATE, ZIP_CODE FROM ADDRESSES INNER JOIN CUSTOMERS
ON ADDRESSES.ADDRESS_ID = CUSTOMERS.CUSTOMER_ID
WHERE CUSTOMERS.EMAIL_ADDRESS = 'allan.sherwood@yahoo.com';

-- 4-03
SELECT FIRST_NAME, LAST_NAME, LINE1, CITY, STATE, ZIP_CODE FROM ADDRESSES INNER JOIN CUSTOMERS
ON ADDRESSES.ADDRESS_ID = CUSTOMERS.SHIPPING_ADDRESS_ID;

-- 4-04
SELECT LAST_NAME, FIRST_NAME, ORDER_DATE, PRODUCT_NAME, ITEM_PRICE, DISCOUNT_AMOUNT, QUANTITY FROM CUSTOMERS c INNER JOIN ORDERS o
ON c.CUSTOMER_ID = o.CUSTOMER_ID
INNER JOIN ORDER_ITEMS oi
ON o.ORDER_ID = oi.ORDER_ID
INNER JOIN PRODUCTS p
ON oi.PRODUCT_ID = p.PRODUCT_ID
ORDER BY LAST_NAME, ORDER_DATE, PRODUCT_NAME;

-- 4-05
SELECT p1.PRODUCT_NAME, p2.LIST_PRICE FROM PRODUCTS p1 JOIN PRODUCTS p2
ON (p1.LIST_PRICE = p2.LIST_PRICE AND p1.PRODUCT_ID <> p2.PRODUCT_ID)
ORDER BY PRODUCT_NAME;

-- 4-06
SELECT CATEGORY_NAME, PRODUCT_ID FROM CATEGORIES c FULL OUTER JOIN PRODUCTS p
ON c.CATEGORY_ID = p.CATEGORY_ID
WHERE p.PRODUCT_ID IS NULL;

-- 4-07
SELECT 'SHIPPED' AS SHIP_STATUS, ORDER_ID, ORDER_DATE FROM ORDERS
WHERE SHIP_DATE IS NOT NULL 
UNION
SELECT 'NOT SHIPPED' AS SHIP_STATUS, ORDER_ID, ORDER_DATE FROM ORDERS
WHERE SHIP_DATE IS NULL
ORDER BY ORDER_DATE;