-- HW1.sql -- Homework 1
--
-- KEVIN NGUYEN
-- UT EID: kdn433, UTCS username: kxnguyen
-- CS f347, Spring 2017, Dr. P. Cannata
-- Department of Computer Science, The University of Texas at Austin
--
 
-- 3-01
SELECT PRODUCT_CODE, PRODUCT_NAME, LIST_PRICE, DISCOUNT_PERCENT FROM PRODUCTS
ORDER BY LIST_PRICE DESC

-- 3-02
SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME FROM CUSTOMERS
WHERE LAST_NAME BETWEEN 'M' and 'Z'
ORDER BY LAST_NAME

-- 3-03
SELECT PRODUCT_NAME, LIST_PRICE, DATE_ADDED FROM PRODUCTS
WHERE LIST_PRICE > 500 and LIST_PRICE < 2000
ORDER BY DATE_ADDED DESC

-- 3-04
SELECT PRODUCT_NAME, LIST_PRICE, DISCOUNT_PERCENT, LIST_PRICE*(DISCOUNT_PERCENT/100) AS DISCOUNT_AMOUNT, LIST_PRICE-(LIST_PRICE*(DISCOUNT_PERCENT/100)) AS DISCOUNT_PRICE FROM PRODUCTS
WHERE ROWNUM < 6
ORDER BY DISCOUNT_PRICE DESC

-- 3-05
SELECT ITEM_ID, ITEM_PRICE, DISCOUNT_AMOUNT, QUANTITY, ITEM_PRICE*QUANTITY AS PRICE_TOTAL, DISCOUNT_AMOUNT*QUANTITY AS DISCOUNT_TOTAL, ((ITEM_PRICE-DISCOUNT_AMOUNT)*QUANTITY) AS ITEM_TOTAL FROM ORDER_ITEMS
WHERE ((ITEM_PRICE-DISCOUNT_AMOUNT)*QUANTITY) > 500
ORDER BY ITEM_TOTAL DESC

-- 3-06
SELECT ORDER_ID, ORDER_DATE, SHIP_DATE FROM ORDERS
WHERE SHIP_DATE IS NULL

-- 3-07
SELECT SYSDATE AS TODAY_UNFORMATTED, TO_CHAR(SYSDATE, 'MM-DD-YYYY') AS TODAY_FORMATTED FROM DUAL

-- 3-08
SELECT 100 AS PRICE, .07 AS TAX_RATE, (100*.07) AS TAX_AMOUNT, (100+(100*.07)) AS TOTAL FROM DUAL
